// Generated by CoffeeScript 1.4.0
(function() {
  var current_href, filter, selector, timeout;

  current_href = location.href;

  selector = "#ires a.l, #ires .osl a";

  if ("http://www.google.cn/" === current_href) {
    location.href = "https://www.google.com.hk";
  }

  filter = function(timed) {
    var length, link, links, _i, _len;
    links = document.querySelectorAll(selector);
    length = links.length;
    console.info("find " + length + " links");
    if (length > 0) {
      for (_i = 0, _len = links.length; _i < _len; _i++) {
        link = links[_i];
        link.removeAttribute("onmousedown");
        console.info("" + (_i + 1) + "/" + length + ":" + link.href);
      }
      console.info("OVER");
      if (timed) {
        window.clearInterval(timed);
      }
    }
  };

  if (current_href.indexOf("/search?") > 0) {
    filter();
  } else {
    timeout = window.setInterval(filter(timeout), 999);
  }

}).call(this);
