// Generated by CoffeeScript 1.4.0
(function() {
  var current_href, filter, selector;

  current_href = location.href;

  selector = "#ires";

  if ("http://www.google.cn/" === current_href) {
    location.href = "https://www.google.com.hk";
  }

  filter = function() {
    var box;
    box = document.getElementById("ires");
    box.addEventListener("mouseover", function() {
      var that;
      that = event.target;
      if (that.tagName === "A" && that.onmousedown) {
        that.removeAttribute('onmousedown');
        console.info("remove " + that.href);
      }
    });
  };

  filter();

}).call(this);
