// Generated by CoffeeScript 1.4.0
(function() {
  var filter;

  if ("http://www.google.cn/" === location.href) {
    location.href = "https://www.google.com.hk";
  }

  filter = function() {
    var box, link, links, _i, _len;
    box = document.getElementById("ires");
    if (box) {
      links = box.querySelectorAll("a[onmousedown]");
      for (_i = 0, _len = links.length; _i < _len; _i++) {
        link = links[_i];
        link.removeAttribute('onmousedown');
        console.info("" + (_i + 1) + "/" + _len + ":" + link.href);
      }
    }
  };

  document.addEventListener("DOMNodeInserted", filter);

}).call(this);
